import { NextResponse } from 'next/server'
import { getSession } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require('pdfkit')

function toISODate(d: Date): string {
  return d.toISOString().split('T')[0]
}

export async function GET() {
  const session = await getSession()
  if (!session.userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  const userId = session.userId

  const now = new Date()
  const fourWeeksAgo = new Date(now)
  fourWeeksAgo.setDate(fourWeeksAgo.getDate() - 28)

  // Fetch completions for last 4 weeks
  const completions = await prisma.habitCompletion.findMany({
    where: { userId, completedAt: { gte: fourWeeksAgo } },
    select: { completedAt: true, xpEarned: true },
  })

  const totalXp = completions.reduce((sum, c) => sum + c.xpEarned, 0)
  const totalCompleted = completions.length

  // Best streak: count consecutive days in the last 28 days
  const daySet = new Set(completions.map(c => toISODate(c.completedAt)))
  let bestStreak = 0
  let currentStreak = 0
  for (let i = 27; i >= 0; i--) {
    const d = new Date(now)
    d.setDate(d.getDate() - i)
    const key = toISODate(d)
    if (daySet.has(key)) {
      currentStreak++
      if (currentStreak > bestStreak) bestStreak = currentStreak
    } else {
      currentStreak = 0
    }
  }

  // League W/D/L
  const matches = await prisma.leagueMatch.findMany({
    where: {
      played: true,
      OR: [{ homeTeamId: userId }, { awayTeamId: userId }],
    },
    select: { homeTeamId: true, homeXp: true, awayXp: true },
  })
  let wins = 0, draws = 0, losses = 0
  for (const m of matches) {
    const homeXp = m.homeXp ?? 0
    const awayXp = m.awayXp ?? 0
    const isHome = m.homeTeamId === userId
    const myXp = isHome ? homeXp : awayXp
    const oppXp = isHome ? awayXp : homeXp
    if (myXp > oppXp) wins++
    else if (myXp === oppXp) draws++
    else losses++
  }

  const periodStart = toISODate(fourWeeksAgo)
  const periodEnd = toISODate(now)

  // Generate PDF using pdfkit
  const chunks: Buffer[] = []
  const doc = new PDFDocument({ margin: 50, size: 'A4' })

  doc.on('data', (chunk: Buffer) => chunks.push(chunk))

  // Title
  doc
    .fontSize(24)
    .fillColor('#1a2236')
    .text('HabitManager FC', { align: 'center' })
  doc
    .fontSize(16)
    .fillColor('#d69e2e')
    .text('Weekly Report', { align: 'center' })
  doc.moveDown(0.5)

  // Period
  doc
    .fontSize(11)
    .fillColor('#444444')
    .text(`Period: ${periodStart} to ${periodEnd}`, { align: 'center' })
  doc.moveDown(1.5)

  // Divider
  doc
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .strokeColor('#d69e2e')
    .lineWidth(1.5)
    .stroke()
  doc.moveDown(1)

  // Stats
  const statsY = doc.y
  doc
    .fontSize(13)
    .fillColor('#1a2236')
    .text('Summary', { underline: true })
  doc.moveDown(0.5)

  const stats = [
    ['Total XP Earned', String(totalXp)],
    ['Total Habits Completed', String(totalCompleted)],
    ['Best Streak (days)', String(bestStreak)],
    ['League Record (W/D/L)', `${wins} / ${draws} / ${losses}`],
  ]

  for (const [label, value] of stats) {
    doc
      .fontSize(11)
      .fillColor('#555555')
      .text(label + ':', { continued: true })
      .fillColor('#1a2236')
      .text('  ' + value)
    doc.moveDown(0.3)
  }

  doc.moveDown(1)
  doc
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .strokeColor('#cccccc')
    .lineWidth(0.5)
    .stroke()
  doc.moveDown(1)

  // Footer
  doc
    .fontSize(9)
    .fillColor('#999999')
    .text(`Generated by HabitManager FC on ${new Date().toUTCString()}`, { align: 'center' })

  doc.end()

  // Wait for the document to finish
  const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)
  })

  return new NextResponse(new Uint8Array(pdfBuffer), {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename="hmfc-report.pdf"',
    },
  })
}
